### PR TITLE
Project bootstrap

### PR DESCRIPTION
**Pull request by kaffein**
"It's alive" https://media.giphy.com/media/d3Kq5w84bzlBLVDO/source.gif
-- Dr Frankenstein

can you PTAL @devth :)

thanks

### CODE REVIEW

**Comment by devth** [comment]
@kaffein that was fast 😁 

What do you think about [shadow-cljs](https://shadow-cljs.github.io/docs/UsersGuide.html)? Should we consider it? I've never used it but heard a lot of good things.

**Comment by kaffein** [comment]
Actually we use `shadow-cljs` here 😄so I'd say it is pretty convenient and easy to configure, with very good documentation. And Thomas Heller is very active and helps a lot on Clojurian. So yeah I'd say I'm definitely up for it 🤗👍

**Comment by kaffein** [comment]
Quick question @devth : what do you think about the dependency management ? should we have a pure `shadow-cljs`-managed build and totally strip out leiningen or do you want to continue having the latter ?

**Comment by devth** [comment]
Not sure as I haven’t used shadow. Does it integrate nicely with lein? Instinct would be to keep using lein so we have consistent builds across all Yetibot repos.

**Comment by kaffein** [comment]
Integration with `lein` is pretty good so we can go this way then 👍. I will restore the `project.clj`

**Comment by devth** [comment]
Sounds good! Feel free to suggest otherwise as I'm not the one doing the work, and it's been awhile since I've done any cljs 😄

**Comment by kaffein** [comment]
We're good 😊👍

**Review by devth — APPROVED** [review]

**Comment by devth** [comment]
@kaffein I'll let you merge and create new PRs as you see fit. I'll just review / provide feedback or ideas along the way.

**Comment by kaffein** [comment]
Wow cool 🙏 thanks for your trust 😉!!! I'll do my best 😊 and thanks for your feedbacks

**Comment by kaffein** [comment]
by the way @devth, do I need to have some _rights/roles_ set in order to be able to merge ? I do not seem to have the _merge_ button available at the moment :)

**Comment by devth** [comment]
Sorry about that @kaffein 😅 
Should be good to go now - see https://github.com/orgs/yetibot/teams/frontend/discussions

**Comment by kaffein** [comment]
That's cool 👍😄 thanks a lot 😉

**Pull request merged**
